[package]
name = "tsfile-rust"
authors = ["jfeinauer@hey.com"]
version = "0.1.0"
edition = "2021"

[dependencies]

[profile.release]
# See https://kerkour.com/optimize-rust-binary-size
opt-level = "z"
lto = true
codegen-units = 1
